openapi: 3.0.0
info:
  version: "0.0.0"
  title: VC HTTP API
  description: This is an Experimental Open API Specification for the [VC Data Model](https://www.w3.org/TR/vc-data-model/). 
  license:
    name: W3C Software and Document License
    url: http://www.w3.org/Consortium/Legal/copyright-software.
  contact:
    name: GitHub Source Code
    url: https://github.com/transmute-industries/vc-http-api
tags:
  - name: Issuer
    description: APIs for Issuers.
  - name: Holder
    description: APIs for Holders.
  - name: Verifier
    description: APIs for Verifiers.
  - name: Optional
    description: Optional APIs.
paths:
  /credentials:
    post:
      tags:
        - Issuer
      summary: Issues a credential and returns it in the response body.
      operationId: issueCredential
      description: Issues a credential and returns it in the response body.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IssueCredentialRequest'
        description: Parameters for issuing the credential.
      responses:
        '201':
          description: Credential successfully issued!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IssueCredentialResponse'
        '400':
          description: invalid input!
        '500':
          description: error!
  /presentations:
    post:
      tags:
        - Holder
      summary: Proves a presentation and returns it in the response body.
      operationId: provePresentation
      description: Proves a presentation and returns it in the response body.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProvePresentationRequest'
        description: Parameters for proving the presentation.
      responses:
        '201':
          description: Presentation successfully proved!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProvePresentationResponse'
        '400':
          description: invalid input!
        '500':
          description: error!
  /verifications:
    post:
      tags:
        - Verifier
      summary: Verifies a presentation and returns a verificationResult in the response body.
      operationId: verifyPresentation
      description: Verifies a presentation and returns a verificationResult in the response body.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VerifyPresentationRequest'
        description: Parameters for verifying a presentation.
      responses:
        '200':
          description: Presentation successfully verified!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VerifyPresentationResponse'                
        '400':
          description: invalid input!
        '500':
          description: error!
  
components:
  schemas:
    LinkedDataProofOptions:
      type: object
      additionalProperties: false
      description: Options for specifying how the proof is created.
      properties:
        verificationMethod:
          type: string
          description: The URI of the verificationMethod used for the proof. If ommited a default assertionMethod will be used.
        proofPurpose:
          type: string
          description: The purpose of the proof. If ommited "assertionMethod" will be used.
        created:
          type: string
          description: The date of the proof. If ommited system time will be used.
        challenge:
          type: string
          description: The challenge of the proof. 
        domain:
          type: string
          description: The domain of the proof. 
      example: {
        "verificationMethod": "did:example:123#z6MksHh7qHWvybLg5QTPPdG2DgEjjduBDArV9EF9mRiRzMBN",
        "proofPurpose": "assertionMethod",
        "created": "2020-04-02T18:48:36Z",
        "domain": "example.com",
        "challenge": "d436f0c8-fbd9-4e48-bbb2-55fc5d0920a8"
      }
    IssueCredentialRequest:
      type: object
      properties:
        credential:
          type: object
          description: A JSON-LD Verifiable Credential without a proof.
          additionalProperties: true
          properties:
            "@context":
              type: array
              description: The "@context" of the Verifiable Credential.
          example: {
            "@context": [
              "https://www.w3.org/2018/credentials/v1",
              "https://www.w3.org/2018/credentials/examples/v1"
            ],
            "id": "http://example.gov/credentials/3732",
            "type": ["VerifiableCredential", "UniversityDegreeCredential"],
            "issuer": "did:example:123",
            "issuanceDate": "2020-03-16T22:37:26.544Z",
            "credentialSubject": {
              "id": "did:example:123",
              "degree": {
                "type": "BachelorDegree",
                "name": "Bachelor of Science and Arts"
              }
            },
          }
        options:
          $ref: '#/components/schemas/LinkedDataProofOptions'
    IssueCredentialResponse:
        type: object
        description: A JSON-LD Verifiable Credential without a proof.
        additionalProperties: true
        properties:
          "@context":
            type: array
            description: The "@context" of the Verifiable Credential.
          "proof":
            type: object
            description: The proof of the Verifiable Credential.
        example: {
          "@context": [
            "https://www.w3.org/2018/credentials/v1",
            "https://www.w3.org/2018/credentials/examples/v1"
          ],
          "id": "http://example.gov/credentials/3732",
          "type": ["VerifiableCredential", "UniversityDegreeCredential"],
          "issuer": "did:example:123",
          "issuanceDate": "2020-03-16T22:37:26.544Z",
          "credentialSubject": {
            "id": "did:example:123",
            "degree": {
              "type": "BachelorDegree",
              "name": "Bachelor of Science and Arts"
            }
          },
          "proof": {
              "type": "Ed25519Signature2018",
              "created": "2020-04-02T18:28:08Z",
              "verificationMethod": "did:example:123#z6MksHh7qHWvybLg5QTPPdG2DgEjjduBDArV9EF9mRiRzMBN",
              "proofPurpose": "assertionMethod",
              "jws": "eyJhbGciOiJFZERTQSIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..YtqjEYnFENT7fNW-COD0HAACxeuQxPKAmp4nIl8jYAu__6IH2FpSxv81w-l5PvE1og50tS9tH8WyXMlXyo45CA"
          }
        }
    ProvePresentationRequest:
      type: object
      properties:
        presentation:
          type: object
          description: A JSON-LD Verifiable Presentation without a proof.
          additionalProperties: true
          properties:
            "@context":
              type: array
              description: The "@context" of the Verifiable Credential.
          example: {
          "@context": [
            "https://www.w3.org/2018/credentials/v1",
            "https://www.w3.org/2018/credentials/examples/v1"
          ],
          "holder": "did:example:123",
          "type": "VerifiablePresentation",
          "verifiableCredential": {
            "@context": [
              "https://www.w3.org/2018/credentials/v1",
              "https://www.w3.org/2018/credentials/examples/v1"
            ],
            "id": "http://example.gov/credentials/3732",
            "type": ["VerifiableCredential", "UniversityDegreeCredential"],
            "issuer": "did:example:123",
            "issuanceDate": "2020-03-16T22:37:26.544Z",
            "credentialSubject": {
              "id": "did:example:123",
              "degree": {
                "type": "BachelorDegree",
                "name": "Bachelor of Science and Arts"
              }
            },
            "proof": {
              "type": "Ed25519Signature2018",
              "created": "2020-04-02T18:28:08Z",
              "verificationMethod": "did:example:123#z6MksHh7qHWvybLg5QTPPdG2DgEjjduBDArV9EF9mRiRzMBN",
              "proofPurpose": "assertionMethod",
              "jws": "eyJhbGciOiJFZERTQSIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..YtqjEYnFENT7fNW-COD0HAACxeuQxPKAmp4nIl8jYAu__6IH2FpSxv81w-l5PvE1og50tS9tH8WyXMlXyo45CA"
            }
          }
        }
        options:
          $ref: '#/components/schemas/LinkedDataProofOptions'
    ProvePresentationResponse:
        type: object
        description: A JSON-LD Verifiable Presentation.
        additionalProperties: true
        properties:
          "@context":
            type: array
            description: The "@context" of the Verifiable Presentation.
          "proof":
            type: object
            description: The proof of the Verifiable Presentation.
        example: {
            "@context": [
              "https://www.w3.org/2018/credentials/v1",
              "https://www.w3.org/2018/credentials/examples/v1"
            ],
            "holder": "did:example:123",
            "type": "VerifiablePresentation",
            "verifiableCredential": {
              "@context": [
                "https://www.w3.org/2018/credentials/v1",
                "https://www.w3.org/2018/credentials/examples/v1"
              ],
              "id": "http://example.gov/credentials/3732",
              "type": ["VerifiableCredential", "UniversityDegreeCredential"],
              "issuer": "did:example:123",
              "issuanceDate": "2020-03-16T22:37:26.544Z",
              "credentialSubject": {
                "id": "did:example:123",
                "degree": {
                  "type": "BachelorDegree",
                  "name": "Bachelor of Science and Arts"
                }
              },
              "proof": {
                "type": "Ed25519Signature2018",
                "created": "2020-04-02T18:28:08Z",
                "verificationMethod": "did:example:123#z6MksHh7qHWvybLg5QTPPdG2DgEjjduBDArV9EF9mRiRzMBN",
                "proofPurpose": "assertionMethod",
                "jws": "eyJhbGciOiJFZERTQSIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..YtqjEYnFENT7fNW-COD0HAACxeuQxPKAmp4nIl8jYAu__6IH2FpSxv81w-l5PvE1og50tS9tH8WyXMlXyo45CA"
              }
            },
            "proof": {
              "type": "Ed25519Signature2018",
              "created": "2020-04-02T18:48:36Z",
              "verificationMethod": "did:example:123#z6MkjRagNiMu91DduvCvgEsqLZDVzrJzFrwahc4tXLt9DoHd",
              "proofPurpose": "authentication",
              "challenge": "99612b24-63d9-11ea-b99f-4f66f3e4f81a",
              "domain": "example.com",
              "jws": "eyJhbGciOiJFZERTQSIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..b-o9btxwIMwrXJC3hHxwSWI_ZryUwi41siEVvOhCYigfp68Y_z1Ic5jqBBhezU109kGL7znEiu8r9yIkvfuZCA"
            }
          }
    VerifyPresentationRequest:
      type: object
      properties:
        presentation:
          type: object
          description: A JSON-LD Verifiable Presentation.
          additionalProperties: true
          properties:
            "@context":
              type: array
              description: The "@context" of the Verifiable Credential.
          example: {
            "@context": [
              "https://www.w3.org/2018/credentials/v1",
              "https://www.w3.org/2018/credentials/examples/v1"
            ],
            "holder": "did:example:123",
            "type": "VerifiablePresentation",
            "verifiableCredential": {
              "@context": [
                "https://www.w3.org/2018/credentials/v1",
                "https://www.w3.org/2018/credentials/examples/v1"
              ],
              "id": "http://example.gov/credentials/3732",
              "type": ["VerifiableCredential", "UniversityDegreeCredential"],
              "issuer": "did:example:123",
              "issuanceDate": "2020-03-16T22:37:26.544Z",
              "credentialSubject": {
                "id": "did:example:123",
                "degree": {
                  "type": "BachelorDegree",
                  "name": "Bachelor of Science and Arts"
                }
              },
              "proof": {
                "type": "Ed25519Signature2018",
                "created": "2020-04-02T18:28:08Z",
                "verificationMethod": "did:example:123#z6MksHh7qHWvybLg5QTPPdG2DgEjjduBDArV9EF9mRiRzMBN",
                "proofPurpose": "assertionMethod",
                "jws": "eyJhbGciOiJFZERTQSIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..YtqjEYnFENT7fNW-COD0HAACxeuQxPKAmp4nIl8jYAu__6IH2FpSxv81w-l5PvE1og50tS9tH8WyXMlXyo45CA"
              }
            },
            "proof": {
              "type": "Ed25519Signature2018",
              "created": "2020-04-02T18:48:36Z",
              "verificationMethod": "did:example:123#z6MkjRagNiMu91DduvCvgEsqLZDVzrJzFrwahc4tXLt9DoHd",
              "proofPurpose": "authentication",
              "challenge": "99612b24-63d9-11ea-b99f-4f66f3e4f81a",
              "domain": "example.com",
              "jws": "eyJhbGciOiJFZERTQSIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..b-o9btxwIMwrXJC3hHxwSWI_ZryUwi41siEVvOhCYigfp68Y_z1Ic5jqBBhezU109kGL7znEiu8r9yIkvfuZCA"
            }
          }
        options:
          $ref: '#/components/schemas/LinkedDataProofOptions'
    VerifyPresentationResponse:
      type: object
      additionalProperties: false
      description: Results of performing a verification
      properties:
        checks:
          type: array
          description: The checks that were performed.
      example: { "checks": ["proof"] }
          